name: DevSecOps Pipeline - Java WebApp

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      # -------------------------
      # SAST: Semgrep
      # -------------------------
      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep scan --config=auto --sarif --output=semgrep.sarif

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()

      # -------------------------
      # SAST: SpotBugs + FindSecBugs
      # -------------------------
      - name: Run SpotBugs
        run: |
          mkdir -p spotbugs
          wget https://github.com/spotbugs/spotbugs/releases/download/4.8.3/spotbugs-4.8.3.tgz
          tar -xzf spotbugs-4.8.3.tgz
          spotbugs-4.8.3/bin/spotbugs -textui -effort:max -low -sarif -output spotbugs.sarif target/

      - name: Upload SpotBugs SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: spotbugs.sarif
        if: always()

      # -------------------------
      # SCA: OWASP Dependency-Check
      # -------------------------
      - name: Run OWASP Dependency-Check
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.2/dependency-check-8.4.2-release.zip -o dc.zip
          unzip dc.zip -d dc
          dc/dependency-check/bin/dependency-check.sh --project "JavaApp" --format "SARIF" --out . --scan .
        continue-on-error: true

      - name: Upload Dependency-Check SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: dependency-check-report.sarif
        if: always()

      # -------------------------
      # Secrets Scanning: TruffleHog
      # -------------------------
      - name: Run TruffleHog
        run: |
          pip install trufflehog
          trufflehog filesystem . --json > trufflehog.json
        continue-on-error: true

      # -------------------------
      # Secrets Scanning: Gitleaks
      # -------------------------
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      # -------------------------
      # SBOM: CycloneDX
      # -------------------------
      - name: Generate SBOM with CycloneDX
        run: |
          mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
        continue-on-error: true

      # -------------------------
      # IaC Scan: Checkov
      # -------------------------
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
        continue-on-error: true

      # -------------------------
      # DAST: OWASP ZAP (Optional - if app is running)
      # -------------------------
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
        continue-on-error: true
