name: DevSecOps Pipeline - Java WebApp

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Unit Tests
      run: mvn test

    # ✅ SAST: Semgrep (Manual Install)
    - name: Install Semgrep
      run: |
        python3 -m pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep Scan
      run: semgrep scan --config=auto --sarif --output=semgrep.sarif

    - name: Upload Semgrep SARIF Report
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-report
        path: semgrep.sarif
      if: always()

    # ✅ Secrets Scan: TruffleHog
    - name: Run TruffleHog (Secrets Scan)
      run: trufflehog --json . > trufflehog_report.json

    - name: Upload TruffleHog JSON Report
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-report
        path: trufflehog_report.json
      if: always()

    # ✅ DAST: OWASP ZAP
    - name: Start Java App for ZAP Scan
      run: nohup java -jar target/*.jar & sleep 15

    - name: Run OWASP ZAP Baseline Scan
      run: |
        docker run -v $(pwd):/zap/wrk/:rw --network=host -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:8080 -J zap-report.json -w zap-report.md -r zap-report.html

    - name: Upload OWASP ZAP Report (HTML)
      uses: actions/upload-artifact@v3
      with:
        name: zap-html-report
        path: zap-report.html
      if: always()

    - name: Upload OWASP ZAP Report (JSON)
      uses: actions/upload-artifact@v3
      with:
        name: zap-json-report
        path: zap-report.json
      if: always()

    - name: Upload OWASP ZAP Report (Markdown)
      uses: actions/upload-artifact@v3
      with:
        name: zap-md-report
        path: zap-report.md
      if: always()
