name: DevSecOps Pipeline - Java WebApp

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Unit Tests
      run: mvn test

    # ✅ SAST: Semgrep (Manual Install)
    - name: Install Semgrep
      run: |
        python3 -m pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep Scan
      run: semgrep scan --config=auto --sarif --output=semgrep.sarif

    - name: Upload Semgrep SARIF Report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif
      if: always()

    # ✅ Secrets Scan: TruffleHog
    - name: Run TruffleHog (Secrets Scan)
      uses: trufflesecurity/trufflehog@main
      with:
        path: .

    # ✅ DAST: OWASP ZAP
    - name: Start Java App for ZAP Scan
      run: nohup java -jar target/*.jar & sleep 15

    - name: Run OWASP ZAP Baseline Scan (No GitHub Issue Reporting)
      run: |
        docker pull ghcr.io/zaproxy/zaproxy:stable
        docker run --network=host -v $(pwd):/zap/wrk/:rw \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t http://localhost:8080 \
          -J zap-report.json -w zap-report.md -r zap-report.html \
          -I  # Continue even if warnings found
