name: DevSecOps Pipeline - Java WebApp

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write  # REQUIRED for upload-sarif

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      # ---------------- SEMGREP ----------------
      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep scan --config=auto --sarif --output=semgrep.sarif

      - name: Upload Semgrep SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()

      # ---------------- OWASP DEPENDENCY-CHECK ----------------
      - name: Run OWASP Dependency-Check
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.2/dependency-check-8.4.2-release.zip -o dc.zip
          unzip dc.zip -d dc
          chmod +x dc/dependency-check/bin/dependency-check.sh
          dc/dependency-check/bin/dependency-check.sh \
            --project "JavaApp" \
            --format "SARIF" \
            --out . \
            --scan .
        continue-on-error: true

      - name: Upload Dependency-Check SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: dependency-check-report.sarif
        if: always()

      # ---------------- SPOTBUGS ----------------
      - name: Run SpotBugs
        run: |
          wget https://github.com/spotbugs/spotbugs/releases/download/4.8.3/spotbugs-4.8.3.tgz
          tar -xzf spotbugs-4.8.3.tgz
          chmod +x spotbugs-4.8.3/bin/spotbugs
          spotbugs-4.8.3/bin/spotbugs -textui -effort:max -low -sarif -output spotbugs.sarif target/
        continue-on-error: true

      - name: Upload SpotBugs SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: spotbugs.sarif
        if: always()

      # ---------------- TRUFFLEHOG (Secrets Scan) ----------------
      - name: TruffleHog secrets scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
        continue-on-error: true


